In [2]:
print(123)

123


In [3]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [10]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [11]:
a[2]

np.int64(3)

In [13]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [14]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
n = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
n[0, 1]

np.int64(2)

In [21]:
n[0, 1] = 20
n

array([[ 1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
n[2] = [16, 17, 18, 19, 20]
n

array([[ 1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [25]:
n[:, 3]

array([ 4,  9, 19])

In [27]:
n[:, 3] = [100, 200, 300]
n

array([[  1,  20,   3, 100,   5],
       [  6,   7,   8, 200,  10],
       [ 16,  17,  18, 300,  20]])

In [28]:
np.random.rand(5, 4)

array([[0.62433469, 0.8497732 , 0.68032323, 0.88148427],
       [0.92212243, 0.43895639, 0.04313808, 0.1821833 ],
       [0.16825187, 0.65676699, 0.0847412 , 0.91713506],
       [0.95480256, 0.62526739, 0.84058249, 0.47442215],
       [0.37770625, 0.00438328, 0.92951437, 0.91504863]])

In [37]:
np.random.seed(2)
np.random.rand(5, 4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149, 0.07964548]])

In [39]:
np.random.seed(2)
np.random.randn(5, 4)

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737,  0.50288142, -1.24528809],
       [-1.05795222, -0.90900761,  0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545,  0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122, -0.74787095,  0.00902525]])

In [40]:
np.random.seed(2)
10 * np.random.rand(5, 4)

array([[4.35994902, 0.25926232, 5.49662478, 4.35322393],
       [4.20367802, 3.30334821, 2.04648634, 6.19270966],
       [2.99654674, 2.66827275, 6.21133833, 5.29142094],
       [1.34579945, 5.13578121, 1.84439866, 7.85335148],
       [8.53975293, 4.94236837, 8.46561485, 0.79645477]])

In [42]:
np.random.seed(2)
np.random.randint(low=3, high=5, size=(5, 4))

array([[3, 4, 4, 3],
       [3, 4, 3, 4],
       [3, 4, 3, 4],
       [4, 4, 4, 4],
       [4, 4, 3, 3]])

In [44]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [45]:
a + 1

array([1, 2, 3, 4, 5])

In [46]:
a * 2 

array([0, 2, 4, 6, 8])

In [51]:
b = 10 + ((a * 2) ** 2) / 2
b

array([10., 12., 18., 28., 42.])

In [52]:
a + b

array([10., 13., 20., 31., 46.])

In [53]:
a * b

array([  0.,  12.,  36.,  84., 168.])

In [61]:
b >= 20

array([False, False, False,  True,  True])

In [62]:
b[b >= 20]

array([28., 42.])

In [63]:
b.min()

np.float64(10.0)

In [64]:
b.max()

np.float64(42.0)

In [65]:
b.sum()

np.float64(110.0)

In [66]:
b.mean()

np.float64(22.0)

In [67]:
b.std()

np.float64(11.7983049630021)