In [4]:
print(123)

123


In [5]:
import numpy as np

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [10]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [11]:
a[2]

np.int64(3)

In [12]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [13]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
n = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
n[0, 1]

np.int64(2)

In [19]:
n[0, 1] = 20
n

array([[ 1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
n[2] = [16, 17, 18, 19, 20]
n

array([[ 1, 20,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [21]:
n[:, 3]

array([ 4,  9, 19])

In [22]:
n[:, 3] = [100, 200, 300]
n

array([[  1,  20,   3, 100,   5],
       [  6,   7,   8, 200,  10],
       [ 16,  17,  18, 300,  20]])

In [23]:
np.random.rand(5, 4)

array([[0.75031874, 0.68011195, 0.27491169, 0.53326801],
       [0.60974364, 0.96399148, 0.78443129, 0.05081686],
       [0.72171909, 0.26282606, 0.44722243, 0.15653934],
       [0.87266512, 0.4847108 , 0.58491205, 0.5077395 ],
       [0.5572224 , 0.01081344, 0.79691665, 0.09231508]])

In [24]:
np.random.seed(2)
np.random.rand(5, 4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149, 0.07964548]])

In [25]:
np.random.seed(2)
np.random.randn(5, 4)

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737,  0.50288142, -1.24528809],
       [-1.05795222, -0.90900761,  0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545,  0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122, -0.74787095,  0.00902525]])

In [26]:
np.random.seed(2)
10 * np.random.rand(5, 4)

array([[4.35994902, 0.25926232, 5.49662478, 4.35322393],
       [4.20367802, 3.30334821, 2.04648634, 6.19270966],
       [2.99654674, 2.66827275, 6.21133833, 5.29142094],
       [1.34579945, 5.13578121, 1.84439866, 7.85335148],
       [8.53975293, 4.94236837, 8.46561485, 0.79645477]])

In [27]:
np.random.seed(2)
np.random.randint(low=3, high=5, size=(5, 4))

array([[3, 4, 4, 3],
       [3, 4, 3, 4],
       [3, 4, 3, 4],
       [4, 4, 4, 4],
       [4, 4, 3, 3]])

In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
a + 1

array([1, 2, 3, 4, 5])

In [30]:
a * 2 

array([0, 2, 4, 6, 8])

In [31]:
b = 10 + ((a * 2) ** 2) / 2
b

array([10., 12., 18., 28., 42.])

In [32]:
a + b

array([10., 13., 20., 31., 46.])

In [33]:
a * b

array([  0.,  12.,  36.,  84., 168.])

In [34]:
b >= 20

array([False, False, False,  True,  True])

In [35]:
b[b >= 20]

array([28., 42.])

In [36]:
b.min()

np.float64(10.0)

In [37]:
b.max()

np.float64(42.0)

In [38]:
b.sum()

np.float64(110.0)

In [39]:
b.mean()

np.float64(22.0)

In [40]:
b.std()

np.float64(11.7983049630021)

In [41]:
def vector_vector_multiplication(a, b):
    assert a.shape[0] == b.shape[0], "Vectors must be the same length"

    n = a.shape[0]
    result = 0
    for i in range(n):
        result += a[i] * b[i]
    return result

In [42]:
vector_vector_multiplication(a, b)

np.float64(300.0)

In [43]:
def matrix_multiplication(m, n):
    assert m.shape[1] == n.shape[0], "columns of first matrix must match rows of second matrix"

    result = np.zeros((m.shape[0], n.shape[1]))
    for i in range(m.shape[0]):
        for j in range(n.shape[1]):
            for k in range(m.shape[1]):
                result[i, j] += m[i, k] * n[k, j]
    return result

In [46]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])

In [47]:
matrix_multiplication(m, n)

array([[  61.,   85.,   73., 1400.,   85.],
       [ 130.,  217.,  160., 3200.,  190.],
       [ 199.,  349.,  247., 5000.,  295.],
       [ 268.,  481.,  334., 6800.,  400.],
       [ 337.,  613.,  421., 8600.,  505.]])

In [52]:
result = m.dot(n)
result

array([[  61,   85,   73, 1400,   85],
       [ 130,  217,  160, 3200,  190],
       [ 199,  349,  247, 5000,  295],
       [ 268,  481,  334, 6800,  400],
       [ 337,  613,  421, 8600,  505]])

In [51]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
result.dot(I)

array([[  61.,   85.,   73., 1400.,   85.],
       [ 130.,  217.,  160., 3200.,  190.],
       [ 199.,  349.,  247., 5000.,  295.],
       [ 268.,  481.,  334., 6800.,  400.],
       [ 337.,  613.,  421., 8600.,  505.]])

In [56]:
inverse = np.linalg.pinv(result)
inverse

array([[ 1.37107419e-02,  8.67073291e-03,  3.63072393e-03,
        -1.40928506e-03, -6.44929405e-03],
       [-3.28770562e-02, -2.07891934e-02, -8.70133060e-03,
         3.38653220e-03,  1.54743950e-02],
       [ 9.99038291e-03,  6.31825800e-03,  2.64613308e-03,
        -1.02599183e-03, -4.69811674e-03],
       [ 9.25674669e-04,  5.99887383e-04,  2.74100097e-04,
        -5.16871889e-05, -3.77474475e-04],
       [ 6.27002392e-03,  3.96578308e-03,  1.66154224e-03,
        -6.42698595e-04, -2.94693943e-03]])

In [58]:
result.dot(inverse)

array([[ 6.00000000e-01,  4.00000000e-01,  2.00000000e-01,
        -1.30472889e-15, -2.00000000e-01],
       [ 4.00000000e-01,  3.00000000e-01,  2.00000000e-01,
         1.00000000e-01, -6.17474821e-15],
       [ 2.00000000e-01,  2.00000000e-01,  2.00000000e-01,
         2.00000000e-01,  2.00000000e-01],
       [ 2.53408405e-14,  1.00000000e-01,  2.00000000e-01,
         3.00000000e-01,  4.00000000e-01],
       [-2.00000000e-01,  1.97957969e-14,  2.00000000e-01,
         4.00000000e-01,  6.00000000e-01]])

In [75]:
Vs = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [76]:
Vs.dot(Vs_inv)

array([[ 1.00000000e+00, -2.66453526e-15,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -7.10542736e-15,  1.00000000e+00]])

In [77]:
Vs_inv.dot(Vs)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -8.8817842e-16,  1.0000000e+00]])